import { Agent } from '@/types/agent';

export const mockAgents: Agent[] = [
  {
    id: 1,
    assistant_id: 'asst-justdial-support-001',
    organization_id: 'org-demo-123',
    name: 'JustDial Support Bot',
    description: 'Handles inbound customer support calls for JustDial listings, queries, and complaints.',
    status: 'Active',
    category: 'Customer Support',
    tags: ['support', 'inbound', 'justdial'],
    language_id: 11,
    stt_model_id: 1,
    tts_model_id: 1,
    llm_model_id: 1,
    voice_id: 1,
    prompt: 'You are a friendly and professional customer support agent for JustDial. Help users with their queries about business listings, reviews, and bookings.',
    speech_speed: '1.0',
    pitch: 'medium',
    interruption_level: 'low',
    cutoff_seconds: 3,
    ideal_time_seconds: 120,
    call_end_text: 'Thank you for calling JustDial. Have a great day!',
    max_token: 1024,
    temperature: '0.7',
    memory_enabled: true,
    max_memory_retrieval: 5,
    initial_message: 'Hello! Welcome to JustDial customer support. How can I help you today?',
    call_recording: true,
    barge_in: true,
    voice_activity_detection: true,
    noise_suppression: true,
    function_calling: false,
    functions: [],
    max_call_duration: 600,
    silence_timeout: 10,
    is_transferable: true,
    transfer_number: '+919876543210',
    filler_message: ['Let me check that for you...', 'One moment please...'],
    function_filler_message: [],
    training_status: 'trained',
    logo_file_url: null,
    logo_file_type: null,
    logo_file_size: null,
    is_active: true,
    is_deleted: false,
    deleted_until: null,
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-03-20T11:30:00Z',
    calls_today: 48,
    avg_duration: '2:45',
    last_active: '2026-03-26T13:55:00Z',
  },
  {
    id: 2,
    assistant_id: 'asst-sales-assistant-002',
    organization_id: 'org-demo-123',
    name: 'Sales Assistant',
    description: 'Outbound sales agent for promoting JustDial premium business listing packages.',
    status: 'Active',
    category: 'Sales',
    tags: ['sales', 'outbound', 'premium'],
    language_id: 11,
    stt_model_id: 1,
    tts_model_id: 1,
    llm_model_id: 1,
    voice_id: 2,
    prompt: 'You are an enthusiastic sales agent for JustDial. Your goal is to explain the benefits of premium business listings and help businesses grow their online presence.',
    speech_speed: '1.1',
    pitch: 'high',
    interruption_level: 'medium',
    cutoff_seconds: 2,
    ideal_time_seconds: 180,
    call_end_text: 'Thank you for your time. Our team will follow up with you shortly.',
    max_token: 1024,
    temperature: '0.8',
    memory_enabled: true,
    max_memory_retrieval: 5,
    initial_message: 'Hi! I am calling from JustDial regarding an exclusive offer for your business. Do you have a moment?',
    call_recording: true,
    barge_in: false,
    voice_activity_detection: true,
    noise_suppression: true,
    function_calling: true,
    functions: [],
    max_call_duration: 900,
    silence_timeout: 8,
    is_transferable: true,
    transfer_number: '+919876543211',
    filler_message: ['That is a great question...', 'Absolutely...'],
    function_filler_message: ['Let me pull up the pricing for you...'],
    training_status: 'trained',
    logo_file_url: null,
    logo_file_type: null,
    logo_file_size: null,
    is_active: true,
    is_deleted: false,
    deleted_until: null,
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-03-18T14:00:00Z',
    calls_today: 32,
    avg_duration: '4:12',
    last_active: '2026-03-26T12:30:00Z',
  },
  {
    id: 3,
    assistant_id: 'asst-booking-agent-003',
    organization_id: 'org-demo-123',
    name: 'Booking Agent',
    description: 'Assists customers with appointment scheduling and service bookings through JustDial.',
    status: 'Active',
    category: 'Booking',
    tags: ['booking', 'appointments', 'scheduling'],
    language_id: 11,
    stt_model_id: 1,
    tts_model_id: 2,
    llm_model_id: 1,
    voice_id: 3,
    prompt: 'You are a helpful booking agent for JustDial. Assist customers in scheduling appointments with local businesses, confirming bookings, and sending reminders.',
    speech_speed: '1.0',
    pitch: 'medium',
    interruption_level: 'low',
    cutoff_seconds: 3,
    ideal_time_seconds: 150,
    call_end_text: 'Your booking is confirmed. You will receive a confirmation shortly. Goodbye!',
    max_token: 1024,
    temperature: '0.6',
    memory_enabled: true,
    max_memory_retrieval: 10,
    initial_message: 'Hello! I am your JustDial booking assistant. How can I help you schedule an appointment today?',
    call_recording: true,
    barge_in: true,
    voice_activity_detection: true,
    noise_suppression: true,
    function_calling: true,
    functions: [],
    max_call_duration: 480,
    silence_timeout: 12,
    is_transferable: false,
    transfer_number: null,
    filler_message: ['Let me check availability...', 'Just a moment...'],
    function_filler_message: ['Checking the calendar...'],
    training_status: 'trained',
    logo_file_url: null,
    logo_file_type: null,
    logo_file_size: null,
    is_active: true,
    is_deleted: false,
    deleted_until: null,
    created_at: '2026-02-01T08:00:00Z',
    updated_at: '2026-03-22T09:45:00Z',
    calls_today: 61,
    avg_duration: '3:28',
    last_active: '2026-03-26T14:10:00Z',
  },
  {
    id: 4,
    assistant_id: 'asst-customer-care-004',
    organization_id: 'org-demo-123',
    name: 'Customer Care',
    description: 'Handles escalations and complex customer care issues for JustDial users.',
    status: 'Active',
    category: 'Customer Support',
    tags: ['care', 'escalation', 'complex'],
    language_id: 11,
    stt_model_id: 2,
    tts_model_id: 1,
    llm_model_id: 1,
    voice_id: 1,
    prompt: 'You are a senior customer care specialist for JustDial. Handle escalated complaints with empathy, provide solutions, and ensure customer satisfaction.',
    speech_speed: '0.9',
    pitch: 'low',
    interruption_level: 'low',
    cutoff_seconds: 4,
    ideal_time_seconds: 240,
    call_end_text: 'We sincerely apologize for the inconvenience. Your issue has been escalated and we will resolve it within 24 hours.',
    max_token: 2048,
    temperature: '0.5',
    memory_enabled: true,
    max_memory_retrieval: 15,
    initial_message: 'Hello, this is JustDial customer care. I understand you need assistance. Please tell me about your concern.',
    call_recording: true,
    barge_in: true,
    voice_activity_detection: true,
    noise_suppression: true,
    function_calling: false,
    functions: [],
    max_call_duration: 1200,
    silence_timeout: 15,
    is_transferable: true,
    transfer_number: '+919876543212',
    filler_message: ['I completely understand your concern...', 'I apologize for the trouble...'],
    function_filler_message: [],
    training_status: 'trained',
    logo_file_url: null,
    logo_file_type: null,
    logo_file_size: null,
    is_active: true,
    is_deleted: false,
    deleted_until: null,
    created_at: '2026-01-20T11:00:00Z',
    updated_at: '2026-03-25T16:00:00Z',
    calls_today: 19,
    avg_duration: '6:55',
    last_active: '2026-03-26T11:20:00Z',
  },
  {
    id: 6,
    assistant_id: 'demo-test-agent-001',
    organization_id: 'org-demo-123',
    name: '🧪 Demo Test Agent',
    description: 'Pre-configured demo agent for testing all UI features, buttons, and API flows. Click "Test Agent" to open the live call simulator.',
    status: 'Active',
    category: 'Customer Service',
    tags: ['demo', 'test', 'mock', 'all-features'],
    language_id: 11,
    stt_model_id: 1,
    tts_model_id: 1,
    llm_model_id: 1,
    voice_id: 1,
    prompt: 'You are a demo AI agent. Respond helpfully to any question to demonstrate the voice agent capabilities.',
    speech_speed: '1.0',
    pitch: 'medium',
    interruption_level: 'low',
    cutoff_seconds: 3,
    ideal_time_seconds: 120,
    call_end_text: 'This was the demo agent. All buttons and features are working correctly. Goodbye!',
    max_token: 1024,
    temperature: '0.7',
    memory_enabled: true,
    max_memory_retrieval: 5,
    initial_message: 'Hello! I am the Demo Test Agent. I am here to help you test all the platform features. How can I assist you?',
    call_recording: true,
    barge_in: true,
    voice_activity_detection: true,
    noise_suppression: true,
    function_calling: true,
    functions: [],
    max_call_duration: 300,
    silence_timeout: 10,
    is_transferable: true,
    transfer_number: '+911234567890',
    filler_message: ['Testing...', 'One moment...', 'Processing...'],
    function_filler_message: ['Calling the API...'],
    training_status: 'trained',
    logo_file_url: null,
    logo_file_type: null,
    logo_file_size: null,
    is_active: true,
    is_deleted: false,
    deleted_until: null,
    created_at: '2026-03-27T00:00:00Z',
    updated_at: '2026-03-27T00:00:00Z',
    calls_today: 5,
    avg_duration: '1:30',
    last_active: '2026-03-27T12:00:00Z',
  },
  {
    id: 5,
    assistant_id: 'asst-feedback-collector-005',
    organization_id: 'org-demo-123',
    name: 'Feedback Collector',
    description: 'Calls customers post-service to collect satisfaction ratings and feedback for JustDial.',
    status: 'Draft',
    category: 'Feedback',
    tags: ['feedback', 'nps', 'survey', 'post-call'],
    language_id: 11,
    stt_model_id: 1,
    tts_model_id: 2,
    llm_model_id: 1,
    voice_id: 2,
    prompt: 'You are a feedback collection agent for JustDial. Conduct short post-service surveys to understand customer satisfaction and gather improvement suggestions.',
    speech_speed: '1.0',
    pitch: 'medium',
    interruption_level: 'medium',
    cutoff_seconds: 3,
    ideal_time_seconds: 90,
    call_end_text: 'Thank you for your valuable feedback. It helps us serve you better!',
    max_token: 512,
    temperature: '0.6',
    memory_enabled: false,
    max_memory_retrieval: 0,
    initial_message: 'Hi! This is JustDial calling to collect feedback about your recent experience. It will only take 2 minutes.',
    call_recording: false,
    barge_in: false,
    voice_activity_detection: true,
    noise_suppression: false,
    function_calling: false,
    functions: [],
    max_call_duration: 300,
    silence_timeout: 8,
    is_transferable: false,
    transfer_number: null,
    filler_message: ['Thank you for sharing...'],
    function_filler_message: [],
    training_status: 'pending',
    logo_file_url: null,
    logo_file_type: null,
    logo_file_size: null,
    is_active: false,
    is_deleted: false,
    deleted_until: null,
    created_at: '2026-03-15T07:00:00Z',
    updated_at: '2026-03-15T07:00:00Z',
    calls_today: 0,
    avg_duration: '0:00',
    last_active: null,
  },
];
