import { AuditLog } from '@/types/audit';

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'al-001',
    organizationId: 'org-demo-123',
    timestamp: '2026-03-26T14:22:10Z',
    user: { id: 'u1', name: 'Demo Admin', email: 'admin@demo.com', role: 'Admin' },
    action: 'login.success',
    resource: 'auth',
    details: 'User logged in successfully',
    ipAddress: '192.168.1.10',
    userAgent: 'Mozilla/5.0',
    location: 'New York, US',
    device: 'Desktop',
    status: 'success',
    severity: 'low',
    metadata: null,
  },
  {
    id: 'al-002',
    organizationId: 'org-demo-123',
    timestamp: '2026-03-26T13:45:00Z',
    user: { id: 'u1', name: 'Demo Admin', email: 'admin@demo.com', role: 'Admin' },
    action: 'agent.created',
    resource: 'agent',
    resourceId: 'a1',
    details: 'Created new agent: Aria Sales Agent',
    ipAddress: '192.168.1.10',
    userAgent: 'Mozilla/5.0',
    location: 'New York, US',
    device: 'Desktop',
    status: 'success',
    severity: 'medium',
    metadata: { agent_name: 'Aria Sales Agent' },
  },
  {
    id: 'al-003',
    organizationId: 'org-demo-123',
    timestamp: '2026-03-26T12:30:00Z',
    user: { id: 'u1', name: 'Demo Admin', email: 'admin@demo.com', role: 'Admin' },
    action: 'provider.configured',
    resource: 'provider',
    resourceId: 'p1',
    details: 'Configured Twilio telephony provider',
    ipAddress: '192.168.1.10',
    userAgent: 'Mozilla/5.0',
    location: 'New York, US',
    device: 'Desktop',
    status: 'success',
    severity: 'high',
    metadata: { provider: 'Twilio' },
  },
  {
    id: 'al-004',
    organizationId: 'org-demo-123',
    timestamp: '2026-03-26T11:15:00Z',
    user: { id: 'u1', name: 'Demo Admin', email: 'admin@demo.com', role: 'Admin' },
    action: 'phone.purchased',
    resource: 'phone',
    resourceId: 'ph1',
    details: 'Phone number +1 (555) 234-5678 purchased',
    ipAddress: '192.168.1.10',
    userAgent: 'Mozilla/5.0',
    location: 'New York, US',
    device: 'Desktop',
    status: 'success',
    severity: 'medium',
    metadata: { phone_number: '+15552345678' },
  },
  {
    id: 'al-005',
    organizationId: 'org-demo-123',
    timestamp: '2026-03-26T10:05:00Z',
    user: { id: 'u1', name: 'Demo Admin', email: 'admin@demo.com', role: 'Admin' },
    action: 'agent.updated',
    resource: 'agent',
    resourceId: 'a2',
    details: 'Updated Support Bot Pro configuration',
    ipAddress: '192.168.1.10',
    userAgent: 'Mozilla/5.0',
    location: 'New York, US',
    device: 'Desktop',
    status: 'success',
    severity: 'low',
    metadata: null,
  },
  {
    id: 'al-006',
    organizationId: 'org-demo-123',
    timestamp: '2026-03-25T16:44:00Z',
    user: { id: 'u1', name: 'Demo Admin', email: 'admin@demo.com', role: 'Admin' },
    action: 'login.failed',
    resource: 'auth',
    details: 'Failed login attempt',
    ipAddress: '203.0.113.5',
    userAgent: 'curl/7.68.0',
    location: 'Unknown',
    device: 'Unknown',
    status: 'failure',
    severity: 'high',
    metadata: { reason: 'Invalid credentials' },
  },
  {
    id: 'al-007',
    organizationId: 'org-demo-123',
    timestamp: '2026-03-25T14:20:00Z',
    user: { id: 'u1', name: 'Demo Admin', email: 'admin@demo.com', role: 'Admin' },
    action: 'call.recorded',
    resource: 'call',
    resourceId: 'c101',
    details: 'Call recording saved for call c101',
    ipAddress: '192.168.1.10',
    userAgent: 'Mozilla/5.0',
    location: 'New York, US',
    device: 'Desktop',
    status: 'success',
    severity: 'low',
    metadata: { duration: 312 },
  },
  {
    id: 'al-008',
    organizationId: 'org-demo-123',
    timestamp: '2026-03-25T09:00:00Z',
    user: { id: 'u1', name: 'Demo Admin', email: 'admin@demo.com', role: 'Admin' },
    action: 'settings.updated',
    resource: 'system',
    details: 'Organization settings updated',
    ipAddress: '192.168.1.10',
    userAgent: 'Mozilla/5.0',
    location: 'New York, US',
    device: 'Desktop',
    status: 'success',
    severity: 'medium',
    metadata: null,
  },
  {
    id: 'al-009',
    organizationId: 'org-demo-123',
    timestamp: '2026-03-24T17:30:00Z',
    user: { id: 'u1', name: 'Demo Admin', email: 'admin@demo.com', role: 'Admin' },
    action: 'data.export',
    resource: 'system',
    details: 'Call logs exported to CSV',
    ipAddress: '192.168.1.10',
    userAgent: 'Mozilla/5.0',
    location: 'New York, US',
    device: 'Desktop',
    status: 'success',
    severity: 'low',
    metadata: { format: 'csv', records: 250 },
  },
  {
    id: 'al-010',
    organizationId: 'org-demo-123',
    timestamp: '2026-03-24T11:10:00Z',
    user: { id: 'u1', name: 'Demo Admin', email: 'admin@demo.com', role: 'Admin' },
    action: 'agent.deleted',
    resource: 'agent',
    resourceId: 'a-old',
    details: 'Deleted inactive agent: Legacy Bot',
    ipAddress: '192.168.1.10',
    userAgent: 'Mozilla/5.0',
    location: 'New York, US',
    device: 'Desktop',
    status: 'success',
    severity: 'high',
    metadata: { agent_name: 'Legacy Bot' },
  },
];
