import { CallLog } from '@/types/call';

export const mockCallLogs: CallLog[] = [
  {
    id: 1,
    call_sid: 'CA001abc123',
    stream_id: 'ST001',
    from_number: '+919876543210',
    to_number: '+911800123456',
    start_time: '2026-03-26T14:10:00Z',
    end_time: '2026-03-26T14:16:12Z',
    duration_seconds: 372,
    recording_link: 'https://recordings.demo.com/CA001abc123.mp3',
    organization_id: 'org-demo-123',
    assistant_id: 'asst-justdial-support-001',
    is_transfered: false,
    transfer_number: null,
    status: 'completed',
    summary: 'Customer Rajesh Kumar called regarding an incorrect charge of ₹499 on his JustDial premium account for March 2026. The AI agent verified his account, confirmed the charge was related to an auto-renewed annual listing plan, explained the renewal policy, and processed a full refund. Customer was satisfied and opted to continue the plan going forward.',
    meta_data: {
      customer_name: 'Rajesh Kumar',
      customer_id: 'CUST-78432',
      account_type: 'Premium Business Listing',
      region: 'Mumbai, Maharashtra',
      language: 'English',
      channel: 'Inbound IVR',
      issue_category: 'Billing',
      sub_category: 'Incorrect Charge',
      resolution_code: 'REFUND_PROCESSED',
      cost_usd: 0.087,
    },
    metrics: {
      callQualityScore: 92,
      sentimentScore: 0.75,
      customerSatisfaction: 4,
      talkTime: 318,
      silenceTime: 54,
      responseTime: 0.38,
      interruptionCount: 2,
      comprehensionScore: 96,
      goalAchievement: 100,
      confidenceScore: 0.94,
      keywordMatches: 7,
    },
    quality: { audioQuality: 4.5, clarityScore: 4.2, connectionQuality: 4.8 },
    sentiment: 'positive',
    outcome: 'resolved',
    tags: ['billing', 'resolved', 'refund', 'premium'],
    call_type: 'inbound',
    insights: [
      { type: 'resolution', title: 'Issue Fully Resolved', confidence: 0.96, description: 'Billing dispute resolved with refund processed in-call' },
      { type: 'sentiment', title: 'Positive Customer Sentiment', confidence: 0.88, description: 'Customer sentiment shifted from frustrated to satisfied during the call' },
      { type: 'upsell', title: 'Retention Opportunity', confidence: 0.72, description: 'Customer agreed to continue premium plan after refund — upsell potential for upgraded tier' },
      { type: 'compliance', title: 'Policy Disclosure', confidence: 0.99, description: 'Agent correctly disclosed auto-renewal terms per compliance guidelines' },
    ],
    key_events: [
      { timestamp: 5, title: 'Call Connected', description: 'Inbound call connected from +919876543210', type: 'connection', severity: 'info' },
      { timestamp: 18, title: 'Customer Identified', description: 'Account verified using phone number — Rajesh Kumar, CUST-78432', type: 'identity', severity: 'info' },
      { timestamp: 42, title: 'Issue Detected', description: 'Billing complaint raised — ₹499 charge disputed', type: 'issue', severity: 'warning' },
      { timestamp: 95, title: 'Account Lookup', description: 'Premium listing plan details retrieved from CRM', type: 'api_call', severity: 'info' },
      { timestamp: 148, title: 'Policy Explained', description: 'Auto-renewal policy explained to customer with dates and amounts', type: 'resolution', severity: 'info' },
      { timestamp: 220, title: 'Refund Initiated', description: 'Refund of ₹499 approved and initiated — expected within 5–7 business days', type: 'action', severity: 'success' },
      { timestamp: 285, title: 'Customer Satisfied', description: 'Customer confirmed satisfaction and agreed to keep premium plan', type: 'sentiment', severity: 'success' },
      { timestamp: 355, title: 'Call Summary Generated', description: 'AI generated call summary and updated CRM record', type: 'system', severity: 'info' },
      { timestamp: 372, title: 'Call Ended', description: 'Call ended normally by customer', type: 'connection', severity: 'info' },
    ],
    customer_satisfaction: 4,
    agent_performance: 5,
    created_at: '2026-03-26T14:10:00Z',
    updated_at: '2026-03-26T14:16:12Z',
    transcripts: [
      { id: 1, call_id: 1, timestamp: '2026-03-26T14:10:05Z', speaker: 'assistant', text: 'Hello! Welcome to JustDial customer support. I\'m Priya, your AI assistant. How can I help you today?', sentiment: 'positive', confidence: 0.98, created_at: '2026-03-26T14:10:05Z' },
      { id: 2, call_id: 1, timestamp: '2026-03-26T14:10:12Z', speaker: 'user', text: 'Hi, I want to complain about a charge on my account. I was charged ₹499 this month but I didn\'t ask for any renewal.', sentiment: 'negative', confidence: 0.94, created_at: '2026-03-26T14:10:12Z' },
      { id: 3, call_id: 1, timestamp: '2026-03-26T14:10:22Z', speaker: 'assistant', text: 'I understand your concern, and I\'m sorry to hear about the unexpected charge. Let me pull up your account right away. Could you please confirm the phone number registered with your JustDial account?', sentiment: 'neutral', confidence: 0.97, created_at: '2026-03-26T14:10:22Z' },
      { id: 4, call_id: 1, timestamp: '2026-03-26T14:10:35Z', speaker: 'user', text: 'It\'s this number only, 9876543210.', sentiment: 'neutral', confidence: 0.96, created_at: '2026-03-26T14:10:35Z' },
      { id: 5, call_id: 1, timestamp: '2026-03-26T14:10:42Z', speaker: 'assistant', text: 'Thank you, Rajesh. I\'ve verified your account. I can see you have a Premium Business Listing plan. Let me check the charge details — please give me just a moment.', sentiment: 'positive', confidence: 0.97, created_at: '2026-03-26T14:10:42Z' },
      { id: 6, call_id: 1, timestamp: '2026-03-26T14:11:35Z', speaker: 'assistant', text: 'I can see the ₹499 charge was for the annual auto-renewal of your Premium Business Listing. Your plan was set to auto-renew on March 15th. This was mentioned in your subscription confirmation email sent on March 10th. I apologize if this wasn\'t clear.', sentiment: 'neutral', confidence: 0.96, created_at: '2026-03-26T14:11:35Z' },
      { id: 7, call_id: 1, timestamp: '2026-03-26T14:11:55Z', speaker: 'user', text: 'I never saw that email. I don\'t want to pay for something I didn\'t knowingly agree to. Can you reverse the charge?', sentiment: 'negative', confidence: 0.93, created_at: '2026-03-26T14:11:55Z' },
      { id: 8, call_id: 1, timestamp: '2026-03-26T14:12:08Z', speaker: 'assistant', text: 'Absolutely, Rajesh. I completely understand. As a courtesy, I\'m happy to process a full refund of ₹499 to your original payment method. The amount should reflect within 5 to 7 business days. Would you like me to proceed with the refund?', sentiment: 'positive', confidence: 0.98, created_at: '2026-03-26T14:12:08Z' },
      { id: 9, call_id: 1, timestamp: '2026-03-26T14:12:22Z', speaker: 'user', text: 'Yes please, go ahead.', sentiment: 'positive', confidence: 0.97, created_at: '2026-03-26T14:12:22Z' },
      { id: 10, call_id: 1, timestamp: '2026-03-26T14:12:28Z', speaker: 'assistant', text: 'Done! I\'ve initiated the refund of ₹499. You\'ll receive a confirmation SMS and email shortly. May I also help you understand the auto-renewal settings so this doesn\'t happen again?', sentiment: 'positive', confidence: 0.97, created_at: '2026-03-26T14:12:28Z' },
      { id: 11, call_id: 1, timestamp: '2026-03-26T14:12:48Z', speaker: 'user', text: 'Yes that would be helpful. Also, is the premium plan actually worth it? What do I get with it?', sentiment: 'positive', confidence: 0.92, created_at: '2026-03-26T14:12:48Z' },
      { id: 12, call_id: 1, timestamp: '2026-03-26T14:13:05Z', speaker: 'assistant', text: 'Great question! With your Premium Listing, you get priority placement in JustDial search results, a verified badge, up to 10 product photos, customer review responses, and detailed analytics on how many people viewed and contacted your business. Many businesses see a 40% increase in inbound calls after upgrading. Would you like me to show you your current listing performance?', sentiment: 'positive', confidence: 0.96, created_at: '2026-03-26T14:13:05Z' },
      { id: 13, call_id: 1, timestamp: '2026-03-26T14:13:40Z', speaker: 'user', text: 'Oh that sounds good. I didn\'t realise all that was included. Maybe I\'ll keep the plan then.', sentiment: 'positive', confidence: 0.94, created_at: '2026-03-26T14:13:40Z' },
      { id: 14, call_id: 1, timestamp: '2026-03-26T14:13:52Z', speaker: 'assistant', text: 'Wonderful! I\'m glad to hear that. I\'ve also updated your auto-renewal preferences — you\'ll now receive a reminder 14 days before any renewal so you can make an informed decision. Is there anything else I can help you with today?', sentiment: 'positive', confidence: 0.98, created_at: '2026-03-26T14:13:52Z' },
      { id: 15, call_id: 1, timestamp: '2026-03-26T14:14:10Z', speaker: 'user', text: 'No, that\'s all. Thank you so much, you were very helpful!', sentiment: 'positive', confidence: 0.97, created_at: '2026-03-26T14:14:10Z' },
      { id: 16, call_id: 1, timestamp: '2026-03-26T14:14:18Z', speaker: 'assistant', text: 'You\'re most welcome, Rajesh! Thank you for calling JustDial. I\'ve sent a summary of this interaction to your registered email. Have a great day!', sentiment: 'positive', confidence: 0.99, created_at: '2026-03-26T14:14:18Z' },
    ],
  },
  {
    id: 2,
    call_sid: 'CA002def456',
    stream_id: 'ST002',
    from_number: '+15558765432',
    to_number: '+15552345678',
    start_time: '2026-03-26T13:30:00Z',
    end_time: '2026-03-26T13:38:45Z',
    duration_seconds: 525,
    recording_link: 'https://recordings.demo.com/CA002def456.mp3',
    organization_id: 'org-demo-123',
    assistant_id: 'a2',
    is_transfered: false,
    transfer_number: null,
    status: 'completed',
    summary: 'Technical support: password reset assistance provided.',
    meta_data: {},
    metrics: { callQualityScore: 88, sentimentScore: 0.62, customerSatisfaction: 4 },
    quality: { audioQuality: 4.3, clarityScore: 4.0, connectionQuality: 4.6 },
    sentiment: 'positive',
    outcome: 'resolved',
    tags: ['tech-support', 'password-reset'],
    call_type: 'inbound',
    insights: [],
    key_events: [],
    customer_satisfaction: 4,
    agent_performance: 4,
    created_at: '2026-03-26T13:30:00Z',
    updated_at: '2026-03-26T13:38:45Z',
    transcripts: [],
  },
  {
    id: 3,
    call_sid: 'CA003ghi789',
    stream_id: 'ST003',
    from_number: '+15557654321',
    to_number: '+15551234567',
    start_time: '2026-03-26T12:05:00Z',
    end_time: '2026-03-26T12:08:20Z',
    duration_seconds: 200,
    recording_link: null,
    organization_id: 'org-demo-123',
    assistant_id: 'a1',
    is_transfered: false,
    transfer_number: null,
    status: 'completed',
    summary: 'Outbound follow-up call. Customer confirmed satisfaction.',
    meta_data: {},
    metrics: { callQualityScore: 95, sentimentScore: 0.88, customerSatisfaction: 5 },
    quality: { audioQuality: 4.7, clarityScore: 4.5, connectionQuality: 4.9 },
    sentiment: 'positive',
    outcome: 'resolved',
    tags: ['follow-up', 'outbound'],
    call_type: 'outbound',
    insights: [],
    key_events: [],
    customer_satisfaction: 5,
    agent_performance: 5,
    created_at: '2026-03-26T12:05:00Z',
    updated_at: '2026-03-26T12:08:20Z',
    transcripts: [],
  },
  {
    id: 4,
    call_sid: 'CA004jkl012',
    stream_id: 'ST004',
    from_number: '+15556543210',
    to_number: '+15552345678',
    start_time: '2026-03-26T11:20:00Z',
    end_time: '2026-03-26T11:32:15Z',
    duration_seconds: 735,
    recording_link: 'https://recordings.demo.com/CA004jkl012.mp3',
    organization_id: 'org-demo-123',
    assistant_id: 'a3',
    is_transfered: true,
    transfer_number: '+15559998877',
    status: 'completed',
    summary: 'Complex billing dispute escalated to human agent.',
    meta_data: {},
    metrics: { callQualityScore: 75, sentimentScore: -0.2, customerSatisfaction: 2 },
    quality: { audioQuality: 3.8, clarityScore: 3.5, connectionQuality: 4.1 },
    sentiment: 'negative',
    outcome: 'escalated',
    tags: ['billing', 'escalated'],
    call_type: 'inbound',
    insights: [{ type: 'escalation', title: 'Escalated', confidence: 0.87, description: 'Customer requested human agent' }],
    key_events: [],
    customer_satisfaction: 2,
    agent_performance: 3,
    created_at: '2026-03-26T11:20:00Z',
    updated_at: '2026-03-26T11:32:15Z',
    transcripts: [],
  },
  {
    id: 5,
    call_sid: 'CA005mno345',
    stream_id: 'ST005',
    from_number: '+15555432109',
    to_number: '+15552345678',
    start_time: '2026-03-26T10:45:00Z',
    end_time: '2026-03-26T10:49:30Z',
    duration_seconds: 270,
    recording_link: null,
    organization_id: 'org-demo-123',
    assistant_id: 'a2',
    is_transfered: false,
    transfer_number: null,
    status: 'completed',
    summary: 'Product information request. Customer satisfied with response.',
    meta_data: {},
    metrics: { callQualityScore: 91, sentimentScore: 0.71, customerSatisfaction: 4 },
    quality: { audioQuality: 4.4, clarityScore: 4.1, connectionQuality: 4.7 },
    sentiment: 'positive',
    outcome: 'resolved',
    tags: ['product-info'],
    call_type: 'inbound',
    insights: [],
    key_events: [],
    customer_satisfaction: 4,
    agent_performance: 4,
    created_at: '2026-03-26T10:45:00Z',
    updated_at: '2026-03-26T10:49:30Z',
    transcripts: [],
  },
  {
    id: 6,
    call_sid: 'CA006pqr678',
    stream_id: 'ST006',
    from_number: '+15554321098',
    to_number: '+15552345678',
    start_time: '2026-03-25T15:10:00Z',
    end_time: '2026-03-25T15:15:40Z',
    duration_seconds: 340,
    recording_link: 'https://recordings.demo.com/CA006pqr678.mp3',
    organization_id: 'org-demo-123',
    assistant_id: 'a1',
    is_transfered: false,
    transfer_number: null,
    status: 'completed',
    summary: 'Account management — updated contact preferences.',
    meta_data: {},
    metrics: { callQualityScore: 89, sentimentScore: 0.65, customerSatisfaction: 4 },
    quality: { audioQuality: 4.2, clarityScore: 4.0, connectionQuality: 4.5 },
    sentiment: 'positive',
    outcome: 'resolved',
    tags: ['account', 'preferences'],
    call_type: 'inbound',
    insights: [],
    key_events: [],
    customer_satisfaction: 4,
    agent_performance: 4,
    created_at: '2026-03-25T15:10:00Z',
    updated_at: '2026-03-25T15:15:40Z',
    transcripts: [],
  },
  {
    id: 7,
    call_sid: 'CA007stu901',
    stream_id: 'ST007',
    from_number: '+15553210987',
    to_number: '+15551234567',
    start_time: '2026-03-25T09:30:00Z',
    end_time: null,
    duration_seconds: 0,
    recording_link: null,
    organization_id: 'org-demo-123',
    assistant_id: 'a4',
    is_transfered: false,
    transfer_number: null,
    status: 'failed',
    summary: null,
    meta_data: {},
    metrics: null,
    quality: null,
    sentiment: 'neutral',
    outcome: 'failed',
    tags: ['failed'],
    call_type: 'outbound',
    insights: [],
    key_events: [],
    customer_satisfaction: null,
    agent_performance: null,
    created_at: '2026-03-25T09:30:00Z',
    updated_at: '2026-03-25T09:30:05Z',
    transcripts: [],
  },
];
