import { CustomerServiceDashboardResponse } from '@/types/analytics';

const now = new Date().toISOString();

export const mockDashboardData: CustomerServiceDashboardResponse = {
  active_calls: { count: 14, timestamp: now },
  queue_length: { count: 3, average_wait_time: 1.4, longest_wait_time: 4.2, timestamp: now },
  agent_utilization: {
    current_value: 78,
    previous_value: 71,
    change_percentage: 9.9,
    trend_direction: 'up',
    utilization_percentage: 78,
    total_agents: 12,
    active_agents: 9,
    timestamp: now,
  },
  satisfaction_score: {
    current_value: 4.6,
    previous_value: 4.4,
    change_percentage: 4.5,
    trend_direction: 'up',
    score: 4.6,
    total_ratings: 320,
    positive_ratings: 294,
    timestamp: now,
  },
  call_volume_trend: {
    time_period: 'today',
    data_points: [
      { timestamp: '2026-03-26T08:00:00Z', value: 18, label: 'Mon' },
      { timestamp: '2026-03-26T09:00:00Z', value: 24, label: 'Tue' },
      { timestamp: '2026-03-26T10:00:00Z', value: 31, label: 'Wed' },
      { timestamp: '2026-03-26T11:00:00Z', value: 27, label: 'Thu' },
      { timestamp: '2026-03-26T12:00:00Z', value: 35, label: 'Fri' },
      { timestamp: '2026-03-26T13:00:00Z', value: 29, label: 'Sat' },
      { timestamp: '2026-03-26T14:00:00Z', value: 22, label: 'Sun' },
    ],
    total_calls: 186,
    average_calls_per_period: 26.6,
  },
  resolution_rate: {
    current_value: 87,
    previous_value: 83,
    change_percentage: 4.8,
    trend_direction: 'up',
    rate_percentage: 87,
    resolved_cases: 162,
    total_cases: 186,
    timestamp: now,
  },
  agent_activity: {
    total_agents: 12,
    active_agents: 9,
    agent_activities: [],
    timestamp: now,
  },
  wait_time: {
    current_value: 1.4,
    previous_value: 2.1,
    change_percentage: -33.3,
    trend_direction: 'down',
    average_wait_time: 1.4,
    median_wait_time: 1.1,
    p95_wait_time: 4.2,
    timestamp: now,
  },
  call_volume_resolution: [
    { date: '2026-03-20T00:00:00Z', call_volume: 142, resolution_count: 120, resolution_rate: 84.5 },
    { date: '2026-03-21T00:00:00Z', call_volume: 158, resolution_count: 136, resolution_rate: 86.1 },
    { date: '2026-03-22T00:00:00Z', call_volume: 171, resolution_count: 149, resolution_rate: 87.1 },
    { date: '2026-03-23T00:00:00Z', call_volume: 163, resolution_count: 141, resolution_rate: 86.5 },
    { date: '2026-03-24T00:00:00Z', call_volume: 177, resolution_count: 155, resolution_rate: 87.6 },
    { date: '2026-03-25T00:00:00Z', call_volume: 180, resolution_count: 157, resolution_rate: 87.2 },
    { date: '2026-03-26T00:00:00Z', call_volume: 186, resolution_count: 162, resolution_rate: 87.1 },
  ],
  issue_type_distribution: {
    total_issues: 186,
    distributions: [
      { issue_type: 'Billing Inquiry', count: 52, percentage: 28 },
      { issue_type: 'Technical Support', count: 47, percentage: 25.3 },
      { issue_type: 'Account Management', count: 38, percentage: 20.4 },
      { issue_type: 'Product Information', count: 30, percentage: 16.1 },
      { issue_type: 'Complaints', count: 19, percentage: 10.2 },
    ],
    timestamp: now,
  },
  agent_performance_overview: {
    total_agents: 12,
    top_performers: [
      { agent_id: 'a1', agent_name: 'Aria Sales Agent', csat_score: 4.9, resolution_rate: 94, average_handle_time: 4.2, first_call_resolution_rate: 88, total_calls: 42 },
      { agent_id: 'a2', agent_name: 'Support Bot Pro', csat_score: 4.7, resolution_rate: 91, average_handle_time: 5.1, first_call_resolution_rate: 85, total_calls: 38 },
      { agent_id: 'a3', agent_name: 'Billing Assistant', csat_score: 4.6, resolution_rate: 89, average_handle_time: 6.3, first_call_resolution_rate: 82, total_calls: 35 },
      { agent_id: 'a4', agent_name: 'Tech Help Desk', csat_score: 4.5, resolution_rate: 87, average_handle_time: 7.8, first_call_resolution_rate: 79, total_calls: 31 },
      { agent_id: 'a5', agent_name: 'Onboarding Guide', csat_score: 4.4, resolution_rate: 85, average_handle_time: 8.2, first_call_resolution_rate: 77, total_calls: 28 },
    ],
    bottom_performers: [],
    average_csat: 4.62,
    average_resolution_rate: 89.2,
    timestamp: now,
  },
  first_call_resolution: {
    current_value: 82,
    previous_value: 79,
    change_percentage: 3.8,
    trend_direction: 'up',
    rate_percentage: 82,
    first_call_resolved: 153,
    total_issues: 186,
    target_rate: 80,
    timestamp: now,
  },
  average_handle_time: {
    current_value: 5.8,
    previous_value: 6.4,
    change_percentage: -9.4,
    trend_direction: 'down',
    handle_time_minutes: 5.8,
    talk_time_minutes: 4.6,
    after_call_work_minutes: 1.2,
    total_calls: 186,
    timestamp: now,
  },
  response_time: {
    current_value: 0.42,
    previous_value: 0.55,
    change_percentage: -23.6,
    trend_direction: 'down',
    average_response_time: 0.42,
    median_response_time: 0.38,
    p95_response_time: 0.91,
    total_calls_answered: 183,
    timestamp: now,
  },
  escalation_rate: {
    current_value: 4.3,
    previous_value: 5.8,
    change_percentage: -25.9,
    trend_direction: 'down',
    rate_percentage: 4.3,
    transferred_calls: 8,
    total_calls: 186,
    timestamp: now,
  },
  dashboard_timestamp: now,
  organization_id: 'org-demo-123',
  time_range: 'today',
  data_freshness: 'live',
};
