import { PhoneNumber } from '@/types/phone-number';

export const mockPhoneNumbers: PhoneNumber[] = [
  {
    id: 1,
    organization_id: 'org-demo-123',
    name: 'Support Line',
    provider_id: 1,
    phone_number: '+912244556677',
    type: 'inbound',
    description: 'Primary inbound support line for JustDial customer queries.',
    is_active: true,
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-03-20T10:00:00Z',
    mapped_assistant: {
      id: 1,
      assistant_id: 'asst-justdial-support-001',
      name: 'JustDial Support Bot',
      status: 'Active',
      is_active: true,
    },
  },
  {
    id: 2,
    organization_id: 'org-demo-123',
    name: 'Sales Outbound',
    provider_id: 1,
    phone_number: '+912244556688',
    type: 'outbound',
    description: 'Outbound line used by the Sales Assistant for premium listing promotions.',
    is_active: true,
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-03-18T14:00:00Z',
    mapped_assistant: {
      id: 2,
      assistant_id: 'asst-sales-assistant-002',
      name: 'Sales Assistant',
      status: 'Active',
      is_active: true,
    },
  },
  {
    id: 3,
    organization_id: 'org-demo-123',
    name: 'Booking Helpline',
    provider_id: 2,
    phone_number: '+912244556699',
    type: 'inbound',
    description: 'Dedicated number for appointment scheduling and booking assistance.',
    is_active: true,
    created_at: '2026-02-01T08:00:00Z',
    updated_at: '2026-03-22T09:45:00Z',
    mapped_assistant: {
      id: 3,
      assistant_id: 'asst-booking-agent-003',
      name: 'Booking Agent',
      status: 'Active',
      is_active: true,
    },
  },
  {
    id: 4,
    organization_id: 'org-demo-123',
    name: 'Customer Care Escalation',
    provider_id: 1,
    phone_number: '+912244556700',
    type: 'both',
    description: 'Escalation line for complex customer care issues.',
    is_active: false,
    created_at: '2026-01-20T11:00:00Z',
    updated_at: '2026-03-25T16:00:00Z',
    mapped_assistant: null,
  },
];
