import { Provider, LLMModel, TTSModel, STTModel, Voice, Language } from '@/types/provider';

export const MOCK_LLM_PROVIDERS: Provider[] = [
  {
    id: 1,
    name: 'openai',
    display_name: 'OpenAI',
    service_type: 'llm',
    description: 'OpenAI language models including GPT-4',
    website: 'https://openai.com',
    region: 'us',
    metadata_json: null,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 2,
    name: 'anthropic',
    display_name: 'Anthropic',
    service_type: 'llm',
    description: 'Anthropic Claude models',
    website: 'https://anthropic.com',
    region: 'us',
    metadata_json: null,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

export const MOCK_TTS_PROVIDERS: Provider[] = [
  {
    id: 3,
    name: 'elevenlabs',
    display_name: 'ElevenLabs',
    service_type: 'tts',
    description: 'High-quality AI voice synthesis',
    website: 'https://elevenlabs.io',
    region: 'us',
    metadata_json: null,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 4,
    name: 'google',
    display_name: 'Google Cloud TTS',
    service_type: 'tts',
    description: 'Google Cloud Text-to-Speech',
    website: 'https://cloud.google.com/text-to-speech',
    region: 'global',
    metadata_json: null,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

export const MOCK_STT_PROVIDERS: Provider[] = [
  {
    id: 5,
    name: 'deepgram',
    display_name: 'Deepgram',
    service_type: 'stt',
    description: 'Real-time speech recognition',
    website: 'https://deepgram.com',
    region: 'us',
    metadata_json: null,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 6,
    name: 'openai_stt',
    display_name: 'OpenAI Whisper',
    service_type: 'stt',
    description: 'OpenAI Whisper speech recognition',
    website: 'https://openai.com/research/whisper',
    region: 'us',
    metadata_json: null,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

export const MOCK_TELEPHONY_PROVIDERS: Provider[] = [
  {
    id: 7,
    name: 'twilio',
    display_name: 'Twilio',
    service_type: 'telephony',
    description: 'Cloud communications platform',
    website: 'https://twilio.com',
    region: 'global',
    metadata_json: null,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

export const MOCK_LLM_MODELS: LLMModel[] = [
  {
    id: 1,
    provider_id: 1,
    model_name: 'gpt-4o',
    display_name: 'GPT-4o',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    provider: MOCK_LLM_PROVIDERS[0],
  },
  {
    id: 2,
    provider_id: 1,
    model_name: 'gpt-4o-mini',
    display_name: 'GPT-4o Mini',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    provider: MOCK_LLM_PROVIDERS[0],
  },
  {
    id: 3,
    provider_id: 2,
    model_name: 'claude-3-5-sonnet-20241022',
    display_name: 'Claude 3.5 Sonnet',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    provider: MOCK_LLM_PROVIDERS[1],
  },
];

export const MOCK_TTS_MODELS: TTSModel[] = [
  {
    id: 1,
    provider_id: 3,
    model_name: 'eleven_multilingual_v2',
    display_name: 'Multilingual v2',
    description: 'High-quality multilingual voice model',
    supported_languages: ['en', 'hi', 'es', 'fr', 'de'],
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    provider: MOCK_TTS_PROVIDERS[0],
  },
  {
    id: 2,
    provider_id: 4,
    model_name: 'standard',
    display_name: 'Standard',
    description: 'Google Cloud TTS standard voices',
    supported_languages: ['en', 'hi', 'es', 'fr', 'de', 'ja', 'zh'],
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    provider: MOCK_TTS_PROVIDERS[1],
  },
];

export const MOCK_STT_MODELS: STTModel[] = [
  {
    id: 1,
    provider_id: 5,
    model_name: 'nova-2',
    display_name: 'Nova-2',
    description: 'Deepgram Nova-2 high-accuracy model',
    supported_languages: ['en', 'hi', 'es', 'fr', 'de'],
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    provider: MOCK_STT_PROVIDERS[0],
  },
  {
    id: 2,
    provider_id: 6,
    model_name: 'whisper-1',
    display_name: 'Whisper',
    description: 'OpenAI Whisper speech recognition',
    supported_languages: ['en', 'hi', 'es', 'fr', 'de', 'ja', 'zh'],
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    provider: MOCK_STT_PROVIDERS[1],
  },
];

export const MOCK_VOICES: Voice[] = [
  {
    id: 1,
    voice_name: 'rachel',
    display_name: 'Rachel',
    description: 'Clear, professional female voice',
    gender: 'female',
    tts_model_id: 1,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 2,
    voice_name: 'adam',
    display_name: 'Adam',
    description: 'Deep, authoritative male voice',
    gender: 'male',
    tts_model_id: 1,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 3,
    voice_name: 'bella',
    display_name: 'Bella',
    description: 'Warm, friendly female voice',
    gender: 'female',
    tts_model_id: 1,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

export const MOCK_LANGUAGES: Language[] = [
  { id: 1, code: 'en', name: 'English' },
  { id: 2, code: 'hi', name: 'Hindi' },
  { id: 3, code: 'es', name: 'Spanish' },
  { id: 4, code: 'fr', name: 'French' },
  { id: 5, code: 'de', name: 'German' },
  { id: 6, code: 'ja', name: 'Japanese' },
  { id: 7, code: 'zh', name: 'Chinese' },
  { id: 8, code: 'ar', name: 'Arabic' },
  { id: 9, code: 'pt', name: 'Portuguese' },
];
